 include: package:very_good_analysis/analysis_options.yaml
 analyzer:
   errors:
     always_put_required_named_parameters_first: ignore
     avoid_redundant_argument_values: ignore
     document_ignores: ignore
     eol_at_end_of_file: ignore
     lines_longer_than_80_chars: ignore
     public_member_api_docs: ignore
     require_trailing_commas: ignore
     sort_constructors_first: ignore
